# Generated by Django 2.1 on 2018-08-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='defaullt',
            field=models.BooleanField(default=False),
        ),
    ]
