# Generated by Django 2.1 on 2018-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(default='', max_length=30, verbose_name='Доставка'),
        ),
    ]
